### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by BlueSolei** [BenjaminKim/dokanx#26]
Hi,

I have few questions.
1. I manage to build DokanX, but didn't manage to find the way to install the dokanx.sys
What is the way to install the driver?
I think that in Dokan it was done automatically by the installer, right?
2. I am running Win7 64 bit, do I need to build the x64 version of the driver, or the x86?
3. I need to be able to dev my FS for Dokan in both x86 and x64 builds, what do I need to config in order to have a x86\x64 DLLs and driver? do the only change is to change the target to x64 in visual studio?

Thanks in advance,

Shaul

**Comment by BenjaminKim** [comment]
> I manage to build DokanX, but didn't manage to find the way to install the dokanx.sys
> What is the way to install the driver?

I wrote how to install the driver in README.md a few days ago.

> I am running Win7 64 bit, do I need to build the x64 version of the driver, or the x86?

Drivers are not supported Wow64 service. It means if you are on 64bit Windows, you have to use x64 driver binary. (But you can run x86 dll/exe on 64bit Windows. That is what Wow64 does.)

> I need to be able to dev my FS for Dokan in both x86 and x64 builds, what do I need to config in order to have a x86\x64 DLLs and driver? do the only change is to change the target to x64 in visual studio?

Yes it is.
