### ISSUE TITLE
Dokany: Dokan fork synced with DokanX

### ISSUE THREAD

**Issue by Maxhy** [BenjaminKim/dokanx#28]
Hi,
Following https://github.com/BenjaminKim/dokanx/issues/22 we created [Dokany](https://github.com/Maxhy/dokany) repository.
It's a Dokan fork synced with DokanX fixes.
We don't have the ambition to maintain an independent Dokan fork (community is too small). The purpose of Dokany is to provide DokanX changes but:
- with clean git history
- with all dokan related projects (.net wrapper, ...)
- with dokan legacy compatibility (no file/lib rename, no function signature changes if not required by bug fixes, no status code change, no too heavy/specific logger)
- using latest WDK8.1 & Visual Studio 2013

All other changes will only be synced according to DokanX changes.

The only additional bug fix not present in DokanX (because it had to be fixed for one of our internal project) is: https://github.com/Maxhy/dokany/commit/2d410022f6e0a539f73c022d893789dff27c8447
Please apply this fix on DokanX too.

GitHub releases are signed using our company code/driver signing certificate ; including x86 and x64 drivers.

**Comment by BenjaminKim** [comment]
Because the title is not focusing about the issue, I made an specific issue.
https://github.com/BenjaminKim/dokanx/issues/29
Good luck to your new project!
