### ISSUE TITLE
Any particular reason why Dokanx.dll exclude exports (.lib) when built as 64bit?

### ISSUE THREAD

**Issue by lalanikarim** [BenjaminKim/dokanx#31]
Hi,
I was running into issues when attempting to compile the user mode libraries and executables under as 64 bit projects. Upon researching the code, I came across the block of code at the bottom in dokan.h which disable exporting symbols. Commenting the outer #ifndef allows building all the modules in 64 bit and the application (MirrorFS) continues to work as expected as it does in 32 bit.
Any particular reason why exports are excluded in 64 bit?

Thanks.
# ifndef _M_X64

  #ifdef _EXPORTING
    #define DOKANAPI __declspec(dllimport) __stdcall
  #else
    #define DOKANAPI __declspec(dllexport) __stdcall
  #endif
# else

  #define DOKANAPI
# endif

**Comment by sherter** [comment]
I had the exact same problem. It would be great if you could add full support for 64bit builds.

**Comment by lalanikarim** [comment]
@sherter It seems to work if you remove the condition and leave the #ifdef _EXPORTING block intact
#ifdef _EXPORTING
#define DOKANAPI __declspec(dllimport) __stdcall
#else
#define DOKANAPI __declspec(dllexport) __stdcall
#endif

Also from the linker options, remove the /MACHINE:X86 from Dokanx project and add x64 configuration for Dokanx, dokanx_mounter, and dokanx_control projects. Check the Common project and add x64 configuration to it as well if needed.

I am building an FS atop DokanX and so far it works well with the configuration described above with both 32 and 64 bit builds.

**Comment by lalanikarim** [comment]
@BenjaminKim Could you please confirm if we "shouldn't" be building DokanX under 64 bit for any reason?

**Comment by lalanikarim** [comment]
Didn't mean to close.

**Comment by BenjaminKim** [comment]
@jimmy00784 No, there is no reason. If DokanX user-mode executable and libraries could be built under 64 bit, it would be nicer. But I guess the original author decided not to build dokan libraries under 64bit, because it is not necessary(because of Wow64), except dokan.sys.
I will make an issue about building 64 bit dokanx libraries. Thanks. You can make pull-request about that, though :+1:
