### ISSUE TITLE
Flush not happening after Write operation

### ISSUE THREAD

**Issue by lalanikarim** [BenjaminKim/dokanx#33]
I've been unable to get FlushFileBuffer method to invoke. Is there a special requirement or criteria that needs to qualify for FlushFileBuffer to work?
As a workaround, I've been managing flush operation within the CloseFile method when needed.

**Comment by BenjaminKim** [comment]
Flush is not happened after _write_ operation.
Flush is happened when an application called `FlushFilebuffer`.
You can issue FlushFileBuffer call by `FileTest` and can watch it from `DebugView` tool as described at README.md.

This screenshot is tip for you :)
![capture](https://cloud.githubusercontent.com/assets/597114/6313689/3fea2554-b9fd-11e4-8550-5000229cba89.PNG)

**Comment by lalanikarim** [comment]
Thanks
