### ISSUE TITLE
Problem using DokanX at Windows 7 64 bits enviroment

### ISSUE THREAD

**Issue by silvadenisaraujo** [BenjaminKim/dokanx#40]
Hello,

I followed the steps for correctily building the driver, and everythings was okay, but when I go to OSR Driver Loader, WLH>AMD64, I can sucessfully Register Service, but I can't Start Service, so I tried mannually at command prompt as administrator, using: net start dokanx and I got an 1275 system error. So, I unregistered the service, reboot the machine and I Disabled the Driver Enforcement, and tried the procedure again and I got the same error. Is there something wrong ? What should be the correct path ?

Thanks in advance.

**Comment by BenjaminKim** [comment]
@silvadenisaraujo What build configuration did you use? You had to build the driver by `x64` config.

**Comment by silvadenisaraujo** [comment]
I used -WIN7 at sys NMAKE. After I changed to -WIN7A64, but the code is not generating a new dokan_win7.sys file. So, now I will download the code again and do the process with -WIN7A64 from the begging. Is that correrct, for Windows 7 64 bits, -WIN7A64. I tried to open OSR at IA64 folder, but it warns me that is not correct.

**Comment by BenjaminKim** [comment]
Why dont you use Visual Studio to build dokanx?

**Comment by silvadenisaraujo** [comment]
I use, but the Visual Studio runs the bat script at some time. So I changed there for -WIN7A64 and it worked fine. If you don't mind I will clone the repository and add some x64 installation information at README.md.  The example mirrorfs, after some time open, it closes automatically and return success. is it supposed to happen ?

**Comment by BenjaminKim** [comment]
why not :) If you have futher question, please make another issue with proper title.
