### ISSUE TITLE
Sharing a DokanX drive

### ISSUE THREAD

**Issue by paulgmiller** [BenjaminKim/dokanx#42]
If I try and share a dokan drive it seems to share fine but on accessing from command line, exporer or anywhere else I get "Device not ready" 

 C:>dir \\millermini\dokan
 The device is not ready.

Which is different than it not existing at all. 
 C:>dir \\millermini\dracula
 The network name cannot be found.

Any idea if this is something fundamental in windows or if there's a workaround?

**Comment by BenjaminKim** [comment]
@paulgmiller  As far as I know, a network redirector can not be reshared.

**Comment by paulgmiller** [comment]
Yep that seems right regardless of dokan or WebDAV or other redirctors. If you do a filesystem minifilter it can be shared but not a lot of open source options there.
