### ISSUE TITLE
mirrorfs.cpp DOKAN_OPTIONS malloc'ed, but dokanOperations pointer checked for result

### ISSUE THREAD

**Issue by gumanoid** [BenjaminKim/dokanx#43]
PDOKAN_OPTIONS dokanOptions = (PDOKAN_OPTIONS)malloc(sizeof(DOKAN_OPTIONS));
if (dokanOperations == nullptr)

should be replaced with

PDOKAN_OPTIONS dokanOptions = (PDOKAN_OPTIONS)malloc(sizeof(DOKAN_OPTIONS));
if (dokanOptions == nullptr)

(this is probably copy-paste issue)

**Comment by BenjaminKim** [comment]
@gumanoid :+1:
