### ISSUE TITLE
Any guarantees of file <-> thread affinity or read/write chunk size?

### ISSUE THREAD

**Issue by gumanoid** [BenjaminKim/dokanx#48]
Is it guaranteed that (consequent) operations on the same file (in virtual FS) will be performed by the same worker thread?
Or is it guaranteed that reading/writing requests will be aligned (e. g. at 16-bytes boundary)?

My case is encrypted file system. Underlying cipher operates on 16-byte blocks, not single byte. Thus, to write 16 bytes at offset 8, I must first read bytes [0..7] and [17..31], and then write bytes [0..31].
The worst possible case is overwriting existing file, writing bytes one by one, making the following event sequence possible:
1. Worker thread A polls request to write single byte at offset 7
2. Worker thread A reads other bytes of 16-byte block (i. e. bytes [0..6] and [8..15]) from underlying file system
3. Context is switched
4. Worker thead B polls request to write single byte at offset 8
5. Worker thread B reads other bytes of the 16-byte block
6. Worker thread B encrypts 16-byte block and writes it back to disk
7. Context is switched
8. Worker thread A encrypts 16-byte block and writes it back to disk
Result: 8th byte is lost (old value is stored)

**Comment by BenjaminKim** [comment]
@gumanoid I don't think it is a good idea encrypting inside filesystem mini filter drivers. You had better write your encryption code at volume driver layer. Then your concern(16 bytes block) will resolve.
[filedisk](https://www.acc.umu.se/~bosse/) is the code you can refer to. Read and test the driver, 
write your encryption code before `ZwWriteFile` and decrypt after `ZwReadFile`. And mount this volume driver under your dokanx filesystem.

**Comment by gumanoid** [comment]
So, the answer is "there's no such guarantees".
Volume-level encryption is not suitable for me since each file is encrypted with it's own key. CTR mode is the solution though, since it allows random-access and has no align restrictions.
Nevertheless, thanks for the link. Maybe it will be useful in the future.
Question can be closed.

**Comment by BenjaminKim** [comment]
Okay good luck! :+1:
